version: "3.2"
services:
  tiled:
    build:
      contenxt: .
    volumes:
      - type: bind
        source: .
        target: /deploy
    environment:
      - TILED_CONFIG=/deploy/config.yml
    ports:
      - 8000:8000
