version: "3.2" # higher config versions may also work; lower will not
services:
  web:
    image: tiled
    volumes:
      - type: bind
        source: .
        target: /deploy
    environment:
      - TILED_CONFIG=/deploy/config.yml
    ports:
      - 8000:8000
